name: Checks
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 27.1
          - 27.2
          - 28.1
          - 28.2
          - 29.1
          - release-snapshot
          - snapshot
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Get emacs ${{ matrix.emacs_version }}
      uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install melpazoid
      run: |
        python -m pip install --upgrade pip
        git clone https://github.com/riscy/melpazoid.git ~/melpazoid
        pip install ~/melpazoid

    - name: Elisp Check
      uses: leotaku/elisp-check@master
      with:
        file: hush.el
        check: melpa
        ignore_warnings: false
        warnings_as_errors: true

    - name: Run Melpazoid
      env:
        LOCAL_REPO: ${{ github.workspace }}
        RECIPE: (hush :repo "tirimia/hush" :fetcher github)
        EXIST_OK: true
      run: make -C ~/melpazoid
